import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/SideBar/SideBar";
import NavBar from "./components/NavBar/NavBar";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "react-datepicker/dist/react-datepicker.css";
import RouteChangeLoading from "./components/RouteChangeLoading/RouteChangeLoading";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex h-screen ">
          <Sidebar />

          <div className="flex-1 relative  grow overflow-auto   bg-[#faf7ff]">
            <NavBar />
            {children}
            <RouteChangeLoading />
            <ToastContainer position="top-right" autoClose={3000} />
          </div>
        </div>
      </body>
    </html>
  );
}
